name: Full Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
      - ci-test-branding

permissions:
  contents: write

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: false
